repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: end-of-file-fixer
        files: \.py$
    -   id: trailing-whitespace
        files: \.py$
    -   id: check-ast
        files: \.py$
    -   id: check-builtin-literals
        files: \.py$
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.4'
    hooks:
      - id: autopep8
        args: [--in-place, --max-line-length=120, --ignore=E203]
        exclude: |
          (?x)^(
              bsi\/.*|
              ci\/.*|
              loader\/.*|
              quality\/.*|
              validation\/.*|
              vr\/.*|
              vsp\/.*|
              delete-this-string-after-end-integration\/.*
          )$
-   repo: https://github.com/psf/black
    rev: '24.3.0'
    hooks:
      - id: black
        args: [--line-length=120]
        exclude: |
          (?x)^(
              bsi\/.*|
              ci\/.*|
              loader\/.*|
              quality\/.*|
              validation\/.*|
              vr\/.*|
              vsp\/.*|
              delete-this-string-after-end-integration\/.*
          )$
-   repo: https://github.com/PyCQA/isort
    rev: '5.13.2'
    hooks:
      - id: isort
        args: ["--profile", "black", "--skip", "__init__.py", "--filter-files"]
        exclude: |
          (?x)^(
              bsi\/.*|
              ci\/.*|
              loader\/.*|
              quality\/.*|
              validation\/.*|
              vr\/.*|
              vsp\/.*|
              delete-this-string-after-end-integration\/.*
          )$
-   repo: https://github.com/PyCQA/flake8
    rev: '7.0.0'
    hooks:
      - id: flake8
        args: ['--max-line-length=120', '--ignore=W605, W503']
        exclude: |
          (?x)^(
              bsi\/.*|
              ci\/.*|
              loader\/.*|
              quality\/.*|
              validation\/.*|
              vr\/.*|
              vsp\/.*|
              delete-this-string-after-end-integration\/.*
          )$
-   repo: https://github.com/thibaudcolas/curlylint
    rev: 'v0.13.1'
    hooks:
      - id: curlylint
